// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPy0QIOtxY29gdolqcdlKERaJwiyD3iQM',
    appId: '1:561814187989:web:2a1bc1240a07cee6bc575c',
    messagingSenderId: '561814187989',
    projectId: 'receipt-cloud-16d79',
    authDomain: 'receipt-cloud-16d79.firebaseapp.com',
    storageBucket: 'receipt-cloud-16d79.firebasestorage.app',
    measurementId: 'G-FZP58VNK18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxruFMJa2ZDyW-lTc2jy0TTJXHTvwqVWU',
    appId: '1:561814187989:android:a7c7a057ccf77752bc575c',
    messagingSenderId: '561814187989',
    projectId: 'receipt-cloud-16d79',
    storageBucket: 'receipt-cloud-16d79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYkKoe_NdLyZOfjBm4KTNlv90yhIzj-ik',
    appId: '1:561814187989:ios:6e7203907a4f878fbc575c',
    messagingSenderId: '561814187989',
    projectId: 'receipt-cloud-16d79',
    storageBucket: 'receipt-cloud-16d79.firebasestorage.app',
    iosClientId: '561814187989-drd62pbj8r9iosphve71joq3pk93ctk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptCloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYkKoe_NdLyZOfjBm4KTNlv90yhIzj-ik',
    appId: '1:561814187989:ios:6e7203907a4f878fbc575c',
    messagingSenderId: '561814187989',
    projectId: 'receipt-cloud-16d79',
    storageBucket: 'receipt-cloud-16d79.firebasestorage.app',
    iosClientId: '561814187989-drd62pbj8r9iosphve71joq3pk93ctk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.receiptCloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPy0QIOtxY29gdolqcdlKERaJwiyD3iQM',
    appId: '1:561814187989:web:81904cd8d438bf23bc575c',
    messagingSenderId: '561814187989',
    projectId: 'receipt-cloud-16d79',
    authDomain: 'receipt-cloud-16d79.firebaseapp.com',
    storageBucket: 'receipt-cloud-16d79.firebasestorage.app',
    measurementId: 'G-GLSTK898E1',
  );
}
